{% set name = "atomic-counter" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/a/atomic_counter/atomic_counter-{{ version }}.tar.gz
  sha256: 1d7dc516776fd9d45de97b8179ebe2e7f5f8edb017ce1d769ff6cd0c6edeff12

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - maturin
  host:
    - python
    - pip
    - maturin
  run:
    - python

test:
  imports:
    - atomic_counter
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/timkpaine/atomic-counter
  summary: 'atomic-counter is a library for generating a monotonically increasing sequence of integers'
  description: 'atomic-counter is a library for generating a monotonically increasing sequence of integers'
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE

extra:
  recipe-maintainers:
    - timkpaine
